name: Deploy Landing Page

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            echo "📂 Moving to project folder..."
            cd /home/ubuntu/ysp-landing

            echo "📥 Pulling latest code..."
            git fetch origin
            git reset --hard origin/main

            # echo "📝 Creating .env file..."
            # echo "${{ secrets.ENV_FILE }}" > .env

            echo "🗑 Removing old build..."
            sudo rm -rf dist

            echo "📦 Installing dependencies..."
            npm install

            echo "🏗 Building project..."
            npm run build

            echo "📁 Checking dist folder..."
            ls -lt dist

            echo "🔄 Fix permissions..."
            sudo chown -R www-data:www-data /home/ubuntu/ysp-landing

            echo "🔄 Reloading Nginx..."
            sudo systemctl reload nginx

            echo "✅ Deployment complete!"
